### ISSUE TITLE
Armour feature suggestion

### ISSUE THREAD

**Issue by zOwenn** [Ellpeck/Rarmor#5]
Hey, im looking forward to getting rarmor on the server Im playing on, and thought of a feature that would be pretty cool. I noticed you could have in built crafting tables and such, would it be possible to add other types of blocks such at the TCon tool station for portable usage? A person in the IRC channel 
(Fandroid) may have left this suggestion, so I apologise if its a repeat

**Comment by canitzp** [comment]
Since Ellpeck isn't developing at Rarmor anymore, can you move this request to this issue tracker: https://github.com/canitzp/Rarmor/issues
